<?=CrudForm::Create("form-1")
	->SetAction(Resource::Local("/api/user/edit"))
	->SetMethod(FormMethod::POST)
	->SetInputColumnSpan(9)
	->SetModel($data->Model)
	->AddChild(HorizontalRule::Create())
	->AddChild(
		LinkButton::Create("link-back")
		->SetLink("user/view/{$data->Model->GetKeyValue()}")
		->SetButtonType(ButtonType::BTN_PRIMARY)
		->SetButtonSize(ControlSize::LARGE)
		->SetText("Back")
	)
	->AddChild(
		Button::Create("btn-save")
		->SetButtonType(ButtonType::BTN_PRIMARY)
		->SetButtonSize(ControlSize::LARGE)
		->SetText("Save")
	)
	->Render()?>
<script>
	$(document).ready(function(){
		$("#form-1").on("submit", function(e){
			e.preventDefault();
		});
		
		$("input[type=display]").prop("readonly",true);
		$("input[type=date]").prop("type","text").datepicker();
	});
</script>