#!/usr/bin/env php
<?php

require_once __DIR__."/references/references.php";
error_reporting(E_ERROR);

$migrator = new MigrationController;

$command = explode(":", $argv[1]);
$context = $argv[2];

switch($command[0])
{
	case "migrate":
		switch($command[1])
		{
			case "make":
				throw new Exception("File successfully made!");
			break;

			default:
				switch($context)
				{
					case "install":
						throw new Exception("Migrate successfully installed!");
					break;
				}
			break;
		}
	break;

	case "new":
		throw new Exception("Creating a new file");
	break;
}

//$first = explode(":", $params[0]);
//$params = array("name" => )

//$status = $frails->run();

//exit($status);